# Generated by Django 5.2.4 on 2025-07-11 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='document',
            field=models.ImageField(blank=None, default='noimage.jpg', null=None, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='nin_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nin_record.ninprofile'),
        ),
        migrations.AlterField(
            model_name='ninprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
