# Generated by Django 5.2.4 on 2025-07-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin_record', '0002_supportingdocument_document_alter_nextofkin_nin_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='father_first_name',
            new_name='guardian_first_name',
        ),
        migrations.RenameField(
            model_name='guardian',
            old_name='father_middle_name',
            new_name='guardian_surname',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='father_nin',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='father_surname',
        ),
        migrations.AddField(
            model_name='guardian',
            name='guardian_middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guardian',
            name='guardian_nin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='father_middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='father_nin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_nin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
