# Generated by Django 5.2.4 on 2025-07-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nin_record', '0003_rename_father_first_name_guardian_guardian_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextofkin',
            old_name='next_of_kin_middel_name',
            new_name='next_of_kin_middle_name',
        ),
    ]
