# Generated by Django 5.2.4 on 2025-07-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nin_record', '0004_rename_next_of_kin_middel_name_nextofkin_next_of_kin_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='next_of_kin_middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='next_of_kin_nin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
